package com.bookingtable.helpers;

import java.time.format.DateTimeFormatter;

import com.bookingtable.models.Invoice;

public class MailHelper {

	public static String HtmlVerify(String code)
    {
        return "\r\n    <table style=\"background-color:#fff;border:0;border-collapse:collapse;border-color:#ddd;border-spacing:0;border-style:solid;border-width:1px;box-sizing:inherit;font:inherit;font-size:100%;margin:0 auto;max-width:680px;padding:0;text-align:center;vertical-align:baseline;width:100%\">\r\n        <tbody style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n            <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n                <td style=\"border:0;border-bottom-color:#ddd;border-bottom-style:solid;border-bottom-width:1px;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:middle\" align=\"left\">\r\n                    <div style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:20px;padding:0;vertical-align:baseline\">\r\n                        <img width=\"119\" height=\"35\" style=\"border:0;border-style:none;box-sizing:inherit;font:inherit;font-size:100%;margin:0;outline:none;padding:0;text-decoration:none;vertical-align:baseline\" src=\"https://iili.io/JXBtmI1.png\" >\r\n                    </div>\r\n                </td>\r\n            </tr>\r\n            <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n                <td style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:middle\">\r\n                    <table style=\"border:0;border-collapse:collapse;border-spacing:0;box-sizing:inherit;display:inline-block;font:inherit;font-size:100%;margin:0;padding:10px 20px;text-align:center;vertical-align:baseline;width:unset\">\r\n                        <tbody style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n                            <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n                                <td style=\"border:0;border-bottom-color:#ddd;border-bottom-style:solid;border-bottom-width:1px;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:middle\">\r\n                                    <table style=\"border:0;border-collapse:collapse;border-spacing:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;max-width:558px;padding:0;text-align:center;vertical-align:baseline;width:100%\">\r\n                                        <tbody style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n                                            <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n                                                <td style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;height:60px;margin:0;padding:0;vertical-align:middle\" align=\"left\">\r\n                                                    <p style=\"border:0;box-sizing:inherit;color:rgb(34,34,34);font:inherit;font-size:20px;font-weight:bold;line-height:20px;margin:0;padding:0;vertical-align:baseline\">Verify your email address</p>\r\n                                                </td>\r\n                                            </tr>\r\n                                            <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n                                                <td style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;height:50px;margin:0;padding:0;vertical-align:middle\" align=\"left\">\r\n                                                    <p style=\"border:0;box-sizing:inherit;color:rgb(34,34,34);font:inherit;font-size:14px;font-weight:300;line-height:20px;margin:0;padding:0;vertical-align:baseline\">You need to verify your email address to continue using your BookingTable account. Enter the following code to verify your email address:</p>\r\n                                                </td>\r\n                                            </tr>\r\n                                            <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n                                                <td style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;height:60px;margin:0;padding:0;vertical-align:middle\" align=\"left\">\r\n                                                    <p style=\"border:0;box-sizing:inherit;color:rgb(34,34,34);font:inherit;font-size:20px;font-weight:bold;line-height:20px;margin:0;padding:0;vertical-align:baseline\">\r\n                                                        <span id=\"m_-8483616267167387556verification-code\">" + code+"</span>\r\n                                                    </p>\r\n                                                </td>\r\n                                            </tr>\r\n                                        </tbody>\r\n                                    </table>\r\n                                </td>\r\n                            </tr>\r\n                        </tbody>\r\n                    </table>\r\n                </td>\r\n            </tr>\r\n        </tbody>\r\n    </table>\r\n   ";
    }
    public static String HtmlNewAccount(String fullname,String username, String password)
    {
        return "\r\n<table style=\"background-color:#fff;border:0;border-collapse:collapse;border-color:#ddd;border-spacing:0;border-style:solid;border-width:1px;box-sizing:inherit;font:inherit;font-size:100%;margin:0 auto;max-width:680px;padding:0;text-align:center;vertical-align:baseline;width:100%\">\r\n    <tbody style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n        <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n            <td style=\"border:0;border-bottom-color:#ddd;border-bottom-style:solid;border-bottom-width:1px;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:middle\" align=\"left\">\r\n                <div style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:20px;padding:0;vertical-align:baseline\">\r\n                    <img width=\"119\" height=\"35\" style=\"border:0;border-style:none;box-sizing:inherit;font:inherit;font-size:100%;margin:0;outline:none;padding:0;text-decoration:none;vertical-align:baseline\" src=\"src=\"https://iili.io/JXBtmI1.png\"\r\n"
        		+ "																		width=\"70\" height=\"40\"\" alt=\"\" class=\"\" data-bit=\"\">\r\n                </div>\r\n            </td>\r\n        </tr>\r\n        <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n            <td style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:middle\">\r\n                <table style=\"border:0;border-collapse:collapse;border-spacing:0;box-sizing:inherit;display:inline-block;font:inherit;font-size:100%;margin:0;padding:10px 20px;text-align:center;vertical-align:baseline;width:unset\">\r\n                    <tbody style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n                        <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n                            <td style=\"border:0;border-bottom-color:#ddd;border-bottom-style:solid;border-bottom-width:1px;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:middle\">\r\n                                <table style=\"border:0;border-collapse:collapse;border-spacing:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;max-width:558px;padding:0;text-align:center;vertical-align:baseline;width:100%\">\r\n                                    <tbody style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n                                        <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n                                            <td style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;height:60px;margin:0;padding:0;vertical-align:middle\" align=\"left\">\r\n                                                <p style=\"border:0;box-sizing:inherit;color:rgb(34,34,34);font:inherit;font-size:20px;font-weight:bold;line-height:20px;margin:0;padding:0;vertical-align:baseline\">Hello " + fullname+"</p>\r\n                                            </td>\r\n                                        </tr>\r\n                                        <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n                                            <td style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;height:50px;margin:0;padding:0;vertical-align:middle\" align=\"left\">\r\n                                                <p style=\"border:0;box-sizing:inherit;color:rgb(34,34,34);font:inherit;font-size:14px;font-weight:300;line-height:20px;margin:0;padding:0;vertical-align:baseline\">We are happy that you have chosen and trusted our company. Below is your account and temporary password.</p>\r\n                                            </td>\r\n                                        </tr>\r\n                                        <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n                                            <td style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;height:60px;margin:0;padding:0;vertical-align:middle\" align=\"left\">\r\n                                                <p style=\"border:0;box-sizing:inherit;color:rgb(34,34,34);font:inherit;font-size:20px;font-weight:bold;line-height:20px;margin:0;padding:0;vertical-align:baseline\">\r\n                                                    <span id=\"m_-8483616267167387556verification-code\">Username : "+username+"</span> \r\n                                                </p>\r\n                                                <p style=\"border:0;box-sizing:inherit;color:rgb(34,34,34);font:inherit;font-size:20px;font-weight:bold;line-height:20px;margin:0;padding:0;vertical-align:baseline;margin-top: 10px;\">\r\n                                                    <span id=\"m_-8483616267167387556verification-code\">Password : "+password+"</span> \r\n                                                </p>\r\n                                            </td>\r\n                                        </tr>\r\n                                    </tbody>\r\n                                </table>\r\n                            </td>\r\n                        </tr>\r\n                    </tbody>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n    </tbody>\r\n</table>\r\n";
    }
    public static String HtmlNotification(Invoice data)
    {
    	DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("HH:mm dd-MM-yyyy");
    	var amount = String.format("%,.2f", (data.getReservation().getDinnerTable().getDinnerTableType().getPrice()/24000));
    	String content = "<style type=\"text/css\">\r\n"
    			+ "    @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,700);\r\n"
    			+ "\r\n"
    			+ "    body {\r\n"
    			+ "        margin: 0;\r\n"
    			+ "        padding: 0;\r\n"
    			+ "        background: #e1e1e1;\r\n"
    			+ "    }\r\n"
    			+ "\r\n"
    			+ "    div,\r\n"
    			+ "    p,\r\n"
    			+ "    a,\r\n"
    			+ "    li,\r\n"
    			+ "    td {\r\n"
    			+ "        -webkit-text-size-adjust: none;\r\n"
    			+ "    }\r\n"
    			+ "\r\n"
    			+ "    .ReadMsgBody {\r\n"
    			+ "        width: 100%;\r\n"
    			+ "        background-color: #ffffff;\r\n"
    			+ "    }\r\n"
    			+ "\r\n"
    			+ "    .ExternalClass {\r\n"
    			+ "        width: 100%;\r\n"
    			+ "        background-color: #ffffff;\r\n"
    			+ "    }\r\n"
    			+ "\r\n"
    			+ "    body {\r\n"
    			+ "        width: 100%;\r\n"
    			+ "        height: 100%;\r\n"
    			+ "        background-color: #e1e1e1;\r\n"
    			+ "        margin: 0;\r\n"
    			+ "        padding: 0;\r\n"
    			+ "        -webkit-font-smoothing: antialiased;\r\n"
    			+ "    }\r\n"
    			+ "\r\n"
    			+ "    html {\r\n"
    			+ "        width: 100%;\r\n"
    			+ "    }\r\n"
    			+ "\r\n"
    			+ "    p {\r\n"
    			+ "        padding: 0 !important;\r\n"
    			+ "        margin-top: 0 !important;\r\n"
    			+ "        margin-right: 0 !important;\r\n"
    			+ "        margin-bottom: 0 !important;\r\n"
    			+ "        margin-left: 0 !important;\r\n"
    			+ "    }\r\n"
    			+ "\r\n"
    			+ "    .visibleMobile {\r\n"
    			+ "        display: none;\r\n"
    			+ "    }\r\n"
    			+ "\r\n"
    			+ "    .hiddenMobile {\r\n"
    			+ "        display: block;\r\n"
    			+ "    }\r\n"
    			+ "\r\n"
    			+ "    @media only screen and (max-width: 600px) {\r\n"
    			+ "        body {\r\n"
    			+ "            width: auto !important;\r\n"
    			+ "        }\r\n"
    			+ "\r\n"
    			+ "        table[class=fullTable] {\r\n"
    			+ "            width: 96% !important;\r\n"
    			+ "            clear: both;\r\n"
    			+ "        }\r\n"
    			+ "\r\n"
    			+ "        table[class=fullPadding] {\r\n"
    			+ "            width: 85% !important;\r\n"
    			+ "            clear: both;\r\n"
    			+ "        }\r\n"
    			+ "\r\n"
    			+ "        table[class=col] {\r\n"
    			+ "            width: 45% !important;\r\n"
    			+ "        }\r\n"
    			+ "\r\n"
    			+ "        .erase {\r\n"
    			+ "            display: none;\r\n"
    			+ "        }\r\n"
    			+ "    }\r\n"
    			+ "\r\n"
    			+ "    @media only screen and (max-width: 420px) {\r\n"
    			+ "        table[class=fullTable] {\r\n"
    			+ "            width: 100% !important;\r\n"
    			+ "            clear: both;\r\n"
    			+ "        }\r\n"
    			+ "\r\n"
    			+ "        table[class=fullPadding] {\r\n"
    			+ "            width: 85% !important;\r\n"
    			+ "            clear: both;\r\n"
    			+ "        }\r\n"
    			+ "\r\n"
    			+ "        table[class=col] {\r\n"
    			+ "            width: 100% !important;\r\n"
    			+ "            clear: both;\r\n"
    			+ "        }\r\n"
    			+ "\r\n"
    			+ "        table[class=col] td {\r\n"
    			+ "            text-align: left !important;\r\n"
    			+ "        }\r\n"
    			+ "\r\n"
    			+ "        .erase {\r\n"
    			+ "            display: none;\r\n"
    			+ "            font-size: 0;\r\n"
    			+ "            max-height: 0;\r\n"
    			+ "            line-height: 0;\r\n"
    			+ "            padding: 0;\r\n"
    			+ "        }\r\n"
    			+ "\r\n"
    			+ "        .visibleMobile {\r\n"
    			+ "            display: block !important;\r\n"
    			+ "        }\r\n"
    			+ "\r\n"
    			+ "        .hiddenMobile {\r\n"
    			+ "            display: none !important;\r\n"
    			+ "        }\r\n"
    			+ "    }\r\n"
    			+ "</style>\r\n"
    			+ "\r\n"
    			+ "\r\n"
    			+ "<!-- Header -->\r\n"
    			+ "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\r\n"
    			+ "    <tr>\r\n"
    			+ "        <td height=\"20\"></td>\r\n"
    			+ "    </tr>\r\n"
    			+ "    <tr>\r\n"
    			+ "        <td>\r\n"
    			+ "            <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\"\r\n"
    			+ "                bgcolor=\"#ffffff\" style=\"border-radius: 10px 10px 0 0;\">\r\n"
    			+ "                <tr class=\"hiddenMobile\">\r\n"
    			+ "                    <td height=\"40\"></td>\r\n"
    			+ "                </tr>\r\n"
    			+ "                <tr class=\"visibleMobile\">\r\n"
    			+ "                    <td height=\"30\"></td>\r\n"
    			+ "                </tr>\r\n"
    			+ "\r\n"
    			+ "                <tr>\r\n"
    			+ "                    <td>\r\n"
    			+ "                        <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\"\r\n"
    			+ "                            class=\"fullPadding\">\r\n"
    			+ "                            <tbody>\r\n"
    			+ "                                <tr>\r\n"
    			+ "                                    <td>\r\n"
    			+ "                                        <table width=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"left\"\r\n"
    			+ "                                            class=\"col\">\r\n"
    			+ "                                            <tbody>\r\n"
    			+ "                                                <tr>\r\n"
    			+ "                                                    <td align=\"left\"> <img\r\n"
    			+ "                                                            src=\"https://iili.io/JXBtmI1.png\"\r\n"
    			+ "																		width=\"70\" height=\"40\" alt=\"logo\" border=\"0\" /></td>\r\n"
    			+ "                                                </tr>\r\n"
    			+ "                                                <tr class=\"hiddenMobile\">\r\n"
    			+ "                                                    <td height=\"40\"></td>\r\n"
    			+ "                                                </tr>\r\n"
    			+ "                                                <tr class=\"visibleMobile\">\r\n"
    			+ "                                                    <td height=\"20\"></td>\r\n"
    			+ "                                                </tr>\r\n"
    			+ "                                                <tr>\r\n"
    			+ "                                                    <td\r\n"
    			+ "                                                        style=\"font-size: 12px; color: #5b5b5b; font-family: 'Open Sans', sans-serif; line-height: 18px; vertical-align: top; text-align: left;\">\r\n"
    			                                                      +" Hello, "+data.getReservation().getCustomer().getFullName()
    			+ "                                                        <br> Thank you for using my service and making an\r\n"
    			+ "                                                        appointment at our store\r\n"
    			+ "                                                    </td>\r\n"
    			+ "                                                </tr>\r\n"
    			+ "                                            </tbody>\r\n"
    			+ "                                        </table>\r\n"
    			+ "                                        <table width=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"right\"\r\n"
    			+ "                                            class=\"col\">\r\n"
    			+ "                                            <tbody>\r\n"
    			+ "                                                <tr class=\"visibleMobile\">\r\n"
    			+ "                                                    <td height=\"20\"></td>\r\n"
    			+ "                                                </tr>\r\n"
    			+ "                                                <tr>\r\n"
    			+ "                                                    <td height=\"5\"></td>\r\n"
    			+ "                                                </tr>\r\n"
    			+ "                                                <tr>\r\n"
    			+ "                                                    <td\r\n"
    			+ "                                                        style=\"font-size: 21px; color: #ff0000; letter-spacing: -1px; font-family: 'Open Sans', sans-serif; line-height: 1; vertical-align: top; text-align: right;\">\r\n"
    			+ "                                                        Invoice\r\n"
    			+ "                                                    </td>\r\n"
    			+ "                                                </tr>\r\n"
    			+ "                                                <tr>\r\n"
    			+ "                                                <tr class=\"hiddenMobile\">\r\n"
    			+ "                                                    <td height=\"50\"></td>\r\n"
    			+ "                                                </tr>\r\n"
    			+ "                                                <tr class=\"visibleMobile\">\r\n"
    			+ "                                                    <td height=\"20\"></td>\r\n"
    			+ "                                                </tr>\r\n"
    			+ "                                                <tr>\r\n"
    			+ "                                                    <td\r\n"
    			+ "                                                        style=\"font-size: 12px; color: #5b5b5b; font-family: 'Open Sans', sans-serif; line-height: 18px; vertical-align: top; text-align: right;\">\r\n"
    			+                                                        "<small>ORDER</small> #" +data.getId()+"<br />"
    			+ "                                                        <small>"+data.getReservation().getCreated().format(dateFormatter)+"</small>\r\n"
    			+ "                                                    </td>\r\n"
    			+ "                                                </tr>\r\n"
    			+ "                                            </tbody>\r\n"
    			+ "                                        </table>\r\n"
    			+ "                                    </td>\r\n"
    			+ "                                </tr>\r\n"
    			+ "                            </tbody>\r\n"
    			+ "                        </table>\r\n"
    			+ "                    </td>\r\n"
    			+ "                </tr>\r\n"
    			+ "            </table>\r\n"
    			+ "        </td>\r\n"
    			+ "    </tr>\r\n"
    			+ "</table>\r\n"
    			+ "<!-- /Header -->\r\n"
    			+ "<!-- Order Details -->\r\n"
    			+ "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\r\n"
    			+ "    <tbody>\r\n"
    			+ "        <tr>\r\n"
    			+ "            <td>\r\n"
    			+ "                <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\"\r\n"
    			+ "                    bgcolor=\"#ffffff\">\r\n"
    			+ "                    <tbody>\r\n"
    			+ "                        <tr>\r\n"
    			+ "                        <tr class=\"hiddenMobile\">\r\n"
    			+ "                            <td height=\"60\"></td>\r\n"
    			+ "                        </tr>\r\n"
    			+ "                        <tr class=\"visibleMobile\">\r\n"
    			+ "                            <td height=\"40\"></td>\r\n"
    			+ "                        </tr>\r\n"
    			+ "                        <tr>\r\n"
    			+ "                            <td>\r\n"
    			+ "                                <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\"\r\n"
    			+ "                                    class=\"fullPadding\">\r\n"
    			+ "                                    <tbody>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <th style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; font-weight: normal; line-height: 1; vertical-align: top; padding: 0 10px 7px 0;\"\r\n"
    			+ "                                                width=\"52%\" align=\"left\">\r\n"
    			+ "                                                Key\r\n"
    			+ "                                            </th>\r\n"
    			+ "                                            <th style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; font-weight: normal; line-height: 1; vertical-align: top; padding: 0 0 7px;\"\r\n"
    			+ "                                                align=\"left\">\r\n"
    			+ "                                                <small></small>\r\n"
    			+ "                                            </th>\r\n"
    			+ "                                            <th style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; font-weight: normal; line-height: 1; vertical-align: top; padding: 0 0 7px;\"\r\n"
    			+ "                                                align=\"center\">\r\n"
    			+ "                                                Value\r\n"
    			+ "                                            </th>\r\n"
    			+ "                                            <th style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #1e2b33; font-weight: normal; line-height: 1; vertical-align: top; padding: 0 0 7px;\"\r\n"
    			+ "                                                align=\"right\">\r\n"
    			+ "\r\n"
    			+ "                                            </th>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td height=\"1\" style=\"background: #bebebe;\" colspan=\"4\"></td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td height=\"10\" colspan=\"4\"></td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #ff0000;  line-height: 18px;  vertical-align: top; padding:10px 0;\"\r\n"
    			+ "                                                class=\"article\">\r\n"
    			+ "                                                Reservation Code\r\n"
    			+ "                                            </td>\r\n"
    			+ "                                            <td colspan=\"3\"\r\n"
    			+ "                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e;  line-height: 18px;  vertical-align: top; padding:10px 0;\">\r\n"
    			+ "                                                <small>"+data.getReservation().getId()+"</small>\r\n"
    			+ "                                            </td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td height=\"1\" colspan=\"4\" style=\"border-bottom:1px solid #e4e4e4\"></td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #ff0000;  line-height: 18px;  vertical-align: top; padding:10px 0;\"\r\n"
    			+ "                                                class=\"article\">Dinner Table</td>\r\n"
    			+ "                                            <td colspan=\"3\"\r\n"
    			+ "                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e;  line-height: 18px;  vertical-align: top; padding:10px 0;\">\r\n"
    			+ "                                                <small> "+data.getReservation().getDinnerTable().getStatus()+"</small>\r\n"
    			+ "                                            </td>\r\n"
    			+ "\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td height=\"1\" colspan=\"4\" style=\"border-bottom:1px solid #e4e4e4\"></td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td height=\"1\" colspan=\"4\" style=\"border-bottom:1px solid #e4e4e4\"></td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #ff0000;  line-height: 18px;  vertical-align: top; padding:10px 0;\"\r\n"
    			+ "                                                class=\"article\">Quantity</td>\r\n"
    			+ "                                            <td colspan=\"3\"\r\n"
    			+ "                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e;  line-height: 18px;  vertical-align: top; padding:10px 0;\">\r\n"
    			+ "                                                <small>"+data.getReservation().getQuantity()+"</small>\r\n"
    			+ "                                            </td>\r\n"
    			+ "\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td height=\"1\" colspan=\"4\" style=\"border-bottom:1px solid #e4e4e4\"></td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #ff0000;  line-height: 18px;  vertical-align: top; padding:10px 0;\"\r\n"
    			+ "                                                class=\"article\">Party Size</td>\r\n"
    			+ "                                            <td colspan=\"3\"\r\n"
    			+ "                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e;  line-height: 18px;  vertical-align: top; padding:10px 0;\">\r\n"
    			+ "                                                <small>"+data.getReservation().getNumberOfPeople()+"</small>\r\n"
    			+ "                                            </td>\r\n"
    			+ "\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td height=\"1\" colspan=\"4\" style=\"border-bottom:1px solid #e4e4e4\"></td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #ff0000;  line-height: 18px;  vertical-align: top; padding:10px 0;\"\r\n"
    			+ "                                                class=\"article\">Restaurant</td>\r\n"
    			+ "                                            <td colspan=\"3\"\r\n"
    			+ "                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e;  line-height: 18px;  vertical-align: top; padding:10px 0;\">\r\n"
    			+ "                                                <small> "+data.getReservation().getRestaurant().getName()+"</small>\r\n"
    			+ "                                            </td>\r\n"
    			+ "\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td height=\"1\" colspan=\"4\" style=\"border-bottom:1px solid #e4e4e4\"></td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #ff0000;  line-height: 18px;  vertical-align: top; padding:10px 0;\"\r\n"
    			+ "                                                class=\"article\">Booking Date</td>\r\n"
    			+ "                                            <td colspan=\"3\"\r\n"
    			+ "                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e;  line-height: 18px;  vertical-align: top; padding:10px 0;\">\r\n"
    			+ "                                                <small>"+data.getReservation().getBookingDate()+"</small>\r\n"
    			+ "                                            </td>\r\n"
    			+ "\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td height=\"1\" colspan=\"4\" style=\"border-bottom:1px solid #e4e4e4\"></td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #ff0000;  line-height: 18px;  vertical-align: top; padding:10px 0;\"\r\n"
    			+ "                                                class=\"article\">Booking Time </td>\r\n"
    			+ "                                            <td colspan=\"3\"\r\n"
    			+ "                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e;  line-height: 18px;  vertical-align: top; padding:10px 0;\">\r\n"
    			+ "                                                <small> "+data.getReservation().getBookingTime()+"</small>\r\n"
    			+ "                                            </td>\r\n"
    			+ "\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td height=\"1\" colspan=\"4\" style=\"border-bottom:1px solid #e4e4e4\"></td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #ff0000;  line-height: 18px;  vertical-align: top; padding:10px 0;\"\r\n"
    			+ "                                                class=\"article\">Status</td>\r\n"
    			+ "                                            <td colspan=\"3\"\r\n"
    			+ "                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e;  line-height: 18px;  vertical-align: top; padding:10px 0;\">\r\n"
    			+ "                                                <small>"+data.getReservation().getReservationStatus().getStatus()+"</small>\r\n"
    			+ "                                            </td>\r\n"
    			+ "\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td height=\"1\" colspan=\"4\" style=\"border-bottom:1px solid #e4e4e4\"></td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                    </tbody>\r\n"
    			+ "                                </table>\r\n"
    			+ "                            </td>\r\n"
    			+ "                        </tr>\r\n"
    			+ "                        <tr>\r\n"
    			+ "                            <td height=\"20\"></td>\r\n"
    			+ "                        </tr>\r\n"
    			+ "                    </tbody>\r\n"
    			+ "                </table>\r\n"
    			+ "            </td>\r\n"
    			+ "        </tr>\r\n"
    			+ "    </tbody>\r\n"
    			+ "</table>\r\n"
    			+ "<!-- /Order Details -->\r\n"
    			+ "<!-- Total -->\r\n"
    			+ "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\r\n"
    			+ "    <tbody>\r\n"
    			+ "        <tr>\r\n"
    			+ "            <td>\r\n"
    			+ "                <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\"\r\n"
    			+ "                    bgcolor=\"#ffffff\">\r\n"
    			+ "                    <tbody>\r\n"
    			+ "                        <tr>\r\n"
    			+ "                            <td>\r\n"
    			+ "\r\n"
    			+ "                                <!-- Table Total -->\r\n"
    			+ "                                <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\"\r\n"
    			+ "                                    class=\"fullPadding\">\r\n"
    			+ "                                    <tbody>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td\r\n"
    			+ "                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e; line-height: 22px; vertical-align: top; text-align:right; \">\r\n"
    			+ "                                                Subtotal\r\n"
    			+ "                                            </td>\r\n"
    			+ "                                            <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e; line-height: 22px; vertical-align: top; text-align:right; white-space:nowrap;\"\r\n"
    			+ "                                                width=\"80\">\r\n"
    			+ "                                               "+amount+"\r\n"
    			+ "                                            </td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td\r\n"
    			+ "                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e; line-height: 22px; vertical-align: top; text-align:right; \">\r\n"
    			+ "                                                Shipping &amp; Handling\r\n"
    			+ "                                            </td>\r\n"
    			+ "                                            <td\r\n"
    			+ "                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e; line-height: 22px; vertical-align: top; text-align:right; \">\r\n"
    			+ "                                                0.00\r\n"
    			+ "                                            </td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td\r\n"
    			+ "                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #000; line-height: 22px; vertical-align: top; text-align:right; \">\r\n"
    			+ "                                                <strong>Grand Total</strong>\r\n"
    			+ "                                            </td>\r\n"
    			+ "                                            <td\r\n"
    			+ "                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #000; line-height: 22px; vertical-align: top; text-align:right; \">\r\n"
    			+ "                                           "+amount+"$</td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                    </tbody>\r\n"
    			+ "                                </table>\r\n"
    			+ "                                <!-- /Table Total -->\r\n"
    			+ "\r\n"
    			+ "                            </td>\r\n"
    			+ "                        </tr>\r\n"
    			+ "                    </tbody>\r\n"
    			+ "                </table>\r\n"
    			+ "            </td>\r\n"
    			+ "        </tr>\r\n"
    			+ "    </tbody>\r\n"
    			+ "</table>\r\n"
    			+ "<!-- /Total -->\r\n"
    			+ "<!-- Information -->\r\n"
    			+ "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\r\n"
    			+ "    <tbody>\r\n"
    			+ "        <tr>\r\n"
    			+ "            <td>\r\n"
    			+ "                <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\"\r\n"
    			+ "                    bgcolor=\"#ffffff\">\r\n"
    			+ "                    <tbody>\r\n"
    			+ "                        <tr>\r\n"
    			+ "                        <tr class=\"hiddenMobile\">\r\n"
    			+ "                            <td height=\"60\"></td>\r\n"
    			+ "                        </tr>\r\n"
    			+ "                        <tr class=\"visibleMobile\">\r\n"
    			+ "                            <td height=\"40\"></td>\r\n"
    			+ "                        </tr>\r\n"
    			+ "                        <tr>\r\n"
    			+ "                            <td>\r\n"
    			+ "                                <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\"\r\n"
    			+ "                                    class=\"fullPadding\">\r\n"
    			+ "                                    <tbody>\r\n"
    			+ "                                        <tr>\r\n"
    			+ "                                            <td>\r\n"
    			+ "                                                <table width=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
    			+ "                                                    align=\"left\" class=\"col\">\r\n"
    			+ "\r\n"
    			+ "                                                    <tbody>\r\n"
    			+ "                                                        <tr>\r\n"
    			+ "                                                            <td\r\n"
    			+ "                                                                style=\"font-size: 11px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 1; vertical-align: top; \">\r\n"
    			+ "                                                                <strong>RESTAURANT INFORMATION</strong>\r\n"
    			+ "                                                            </td>\r\n"
    			+ "                                                        </tr>\r\n"
    			+ "                                                        <tr>\r\n"
    			+ "                                                            <td width=\"100%\" height=\"10\"></td>\r\n"
    			+ "                                                        </tr>\r\n"
    			+ "                                                        <tr>\r\n"
    			+ "                                                            <td\r\n"
    			+ "                                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 20px; vertical-align: top; \">\r\n"
    			+ "                                                                <span> "+data.getReservation().getRestaurant().getCity()+"  </span><br>\r\n"
    			+ "                                                                <span> "+data.getReservation().getRestaurant().getDistrict()+" </span><br>\r\n"
    			+ "                                                                <span> "+data.getReservation().getRestaurant().getWard()+"</span><br>\r\n"
    			+ "                                                                <span> "+data.getReservation().getRestaurant().getAddress()+" </span><br>\r\n"
    			+ "                                                                <span> "+data.getReservation().getRestaurant().getMainPhoneNumber()+" </span></span>\r\n"
    			+ "                                                            </td>\r\n"
    			+ "                                                        </tr>\r\n"
    			+ "                                                    </tbody>\r\n"
    			+ "                                                </table>\r\n"
    			+ "\r\n"
    			+ "\r\n"
    			+ "                                                <table width=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
    			+ "                                                    align=\"right\" class=\"col\">\r\n"
    			+ "                                                    <tbody>"
    			+ "                                                        <tr class=\"visibleMobile\">"
    			+ "                                                            <td height=\"20\"></td>"
    			+ "                                                        </tr>"
    			+ "                                                        <tr>"
    			+ "                                                            <td"
    			+ "                                                                style=\"font-size: 11px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 1; vertical-align: top; \">\r\n"
    			+ "                                                                <strong>CUSTOMER INFORMATION</strong>\r\n"
    			+ "                                                            </td>"
    			+ "                                                        </tr>\r\n"
    			+ "                                                        <tr>\r\n"
    			+ "                                                            <td width=\"100%\" height=\"10\"></td>\r\n"
    			+ "                                                        </tr>\r\n"
    			+ "                                                        <tr>\r\n"
    			+ "                                                            <td\r\n"
    			+ "                                                                style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 20px; vertical-align: top; \">\r\n"
    			+ "                                                                <span> "+data.getReservation().getCustomer().getFullName()+" </span><br>\r\n"
    			+ "                                                                <span> "+data.getReservation().getCustomer().getPhoneNumber()+" </span>\r\n"
    			+ "                                                                <br>\r\n"
    			+ "                                                                <span> "+data.getReservation().getCustomer().getEmail()+"</span>\r\n"
    			+ "                                                            </td>\r\n"
    			+ "                                                        </tr>\r\n"
    			+ "                                                    </tbody>\r\n"
    			+ "                                                </table>\r\n"
    			+ "                                            </td>\r\n"
    			+ "                                        </tr>\r\n"
    			+ "                                    </tbody>\r\n"
    			+ "                                </table>\r\n"
    			+ "                            </td>\r\n"
    			+ "                        </tr>\r\n"
    			+ "                        <tr>\r\n"
    			+ "                            <td>\r\n"
    			+ "\r\n"
    			+ "                            </td>\r\n"
    			+ "                        </tr>\r\n"
    			+ "                        <tr class=\"hiddenMobile\">\r\n"
    			+ "                            <td height=\"60\"></td>\r\n"
    			+ "                        </tr>\r\n"
    			+ "                        <tr class=\"visibleMobile\">\r\n"
    			+ "                            <td height=\"30\"></td>\r\n"
    			+ "                        </tr>\r\n"
    			+ "                    </tbody>\r\n"
    			+ "                </table>\r\n"
    			+ "            </td>\r\n"
    			+ "        </tr>\r\n"
    			+ "    </tbody>\r\n"
    			+ "</table>\r\n"
    			+ "<!-- /Information -->\r\n"
    			+ "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\r\n"
    			+ "\r\n"
    			+ "    <tr>\r\n"
    			+ "        <td>\r\n"
    			+ "            <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\"\r\n"
    			+ "                bgcolor=\"#ffffff\" style=\"border-radius: 0 0 10px 10px;\">\r\n"
    			+ "                <tr>\r\n"
    			+ "                    <td>\r\n"
    			+ "                        <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\"\r\n"
    			+ "                            class=\"fullPadding\">\r\n"
    			+ "                            <tbody>\r\n"
    			+ "                                <tr>\r\n"
    			+ "                                    <td\r\n"
    			+ "                                        style=\"font-size: 12px; color: #5b5b5b; font-family: 'Open Sans', sans-serif; line-height: 18px; vertical-align: top; text-align: left;\">\r\n"
    			+ "                                        Have a nice day.\r\n"
    			+ "                                    </td>\r\n"
    			+ "                                </tr>\r\n"
    			+ "                            </tbody>\r\n"
    			+ "                        </table>\r\n"
    			+ "                    </td>\r\n"
    			+ "                </tr>\r\n"
    			+ "                <tr class=\"spacer\">\r\n"
    			+ "                    <td height=\"50\"></td>\r\n"
    			+ "                </tr>\r\n"
    			+ "\r\n"
    			+ "            </table>\r\n"
    			+ "        </td>\r\n"
    			+ "    </tr>\r\n"
    			+ "    <tr>\r\n"
    			+ "        <td height=\"20\"></td>\r\n"
    			+ "    </tr>\r\n"
    			+ "</table>"
    	;
    	
    	return content;
    }
	
}
